# Generated by Django 5.0 on 2024-01-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('myapp', '0001_initial'), ('myapp', '0002_type_user_rename_name_person_nom_remove_person_age_and_more'), ('myapp', '0003_pokemoninstance_delete_person'), ('myapp', '0004_pokemoninstance_recovery'), ('myapp', '0005_remove_pokemoninstance_niveau'), ('myapp', '0006_alter_pokemon_generation'), ('myapp', '0007_rename_hp_pokemon_hp_max_pokemoninstance_hp_max_and_more'), ('myapp', '0008_pokemoninstance_surnom_alter_pokemoninstance_hp'), ('myapp', '0009_objettype_objet'), ('myapp', '0010_baietype_baie')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mot_de_passe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('hp_max', models.IntegerField()),
                ('attaque', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('sp_attaque', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('recovery', models.IntegerField()),
                ('generation', models.IntegerField(default=1)),
                ('catchphrase', models.CharField(max_length=100)),
                ('type1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_type', to='myapp.type')),
                ('type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_type', to='myapp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(to='myapp.pokemon')),
                ('dresseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=models.IntegerField(default=0))),
                ('attaque', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('sp_attaque', models.IntegerField(default=0)),
                ('sp_defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('recovery', models.IntegerField(default=0)),
                ('hp_max', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('En repos', 'En repos'), ('En combat', 'En combat'), ('KO', 'KO'), ('Mort', 'Mort')], default='En combat', max_length=50)),
                ('surnom', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objet', to='myapp.pokemoninstance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='myapp.user')),
                ('type_objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='myapp.objettype')),
            ],
        ),
        migrations.CreateModel(
            name='BaieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Baie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baie', to='myapp.pokemoninstance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baies', to='myapp.user')),
                ('type_baie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='myapp.baietype')),
            ],
        ),
    ]
