# Generated by Django 5.0 on 2023-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pokemoninstance_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoninstance',
            name='recovery',
            field=models.IntegerField(default=1),
        ),
    ]
