# Generated by Django 5.0 on 2023-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_pokemoninstance_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.IntegerField(default=1),
        ),
    ]
