# Generated by Django 5.0 on 2023-12-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_pokemon_generation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='hp',
            new_name='hp_max',
        ),
        migrations.AddField(
            model_name='pokemoninstance',
            name='hp_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemoninstance',
            name='status',
            field=models.CharField(choices=[('En repos', 'En repos'), ('En combat', 'En combat'), ('KO', 'KO'), ('Mort', 'Mort')], default='En combat', max_length=50),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='attaque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='recovery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='sp_attaque',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='sp_defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemoninstance',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
