# Generated by Django 5.0 on 2024-01-07 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_pokemoninstance_surnom_alter_pokemoninstance_hp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objet', to='myapp.pokemoninstance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objets', to='myapp.user')),
                ('type_objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='myapp.objettype')),
            ],
        ),
    ]
