# Generated by Django 5.0 on 2024-01-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_objettype_objet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Baie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baie', to='myapp.pokemoninstance')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baies', to='myapp.user')),
                ('type_baie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='myapp.baietype')),
            ],
        ),
    ]
